### PR TITLE
Feat: support formData

### PR DESCRIPTION
**Pull request by jeasonstudio**

### CODE REVIEW

**Comment by jeasonstudio** [comment]
> A couple of things:
> 
> can you remove the generated dist files from the PR
> add a unit test to cover the formData change

Done for these.

**Comment by jeasonstudio** [comment]
Waiting for the new veriosn. Thx.

**Comment by carlansley** [comment]
just published new versions of swagger2 and swagger2-koa

**Comment by alexbe** [comment]
Hi,
i got 
{"code":"SWAGGER_REQUEST_VALIDATION_FAILED","errors":[{"expected":{"type":"string"},"error":"data is the wrong type","where":"formData"},{"expected":{"type":"string"},"error":"data is the wrong type","where":"formData"}]}

Please patch it like this:

case 'formData':
-        value = (body || {})[parameter.name];
+       value = (body.fields || {})[parameter.name];

The reason is that the body object consist of two other objects
fields:Object {id: 0, note: "blabla", …}
files:Object {}

and has no parameter.name key

**Comment by carlansley** [comment]
@alexbe can you submit a PR for this that includes a test case.

**Pull request merged**
